
CREATE TABLE "+TABLE_PRODUCT+" ("+COL_ID+" INTEGER PRIMARY KEY AUTOINCREMENT, "+COL_NAME+" TEXT, "+COL_DESC+" TEXT)
DROP TABLE IF EXISTS "+TABLE_PRODUCT+"
DELETE FROM "+TABLE_PRODUCT+" WHERE "+COL_ID+" =